[package]
name = "rfr-convert"
version = "0.0.1"
rust-version = "1.93.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
prost = "0.13"
rfr = { version = "0.0.1", path = "../rfr" }
