[package]
name = "xtask"
version = "0.0.1"
rust-version = "1.93.1"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
prost-build = "0.13"
anyhow = "1.0"
